# fly.toml app configuration file generated for galore-bag-and-story on 2023-08-16T11:55:16+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "galore-bag-and-story"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
